services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes: 
      - db:/var/lib/mysql
    expose: 
      - "3306"
    networks: 
      - inception-network
    env_file: 
      - .env
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    volumes: 
      - wp:/var/www
    expose:
      - "9000"
    networks: 
      - inception-network
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    image: nginx
    volumes: 
      - wp:/var/www
    ports:
      - "443:443"
    networks: 
      - inception-network
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always

# VOLUME
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jisulee/data/mariadb_data
  wp :
    driver : local
    driver_opts :
      type : none
      device : /home/jisulee/data/wordpress_data
      o : bind

# NETWORK
networks :
  inception-network :
    driver : bridge
